kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
  - npm ci
  - npm run build
  
- name: upload
  image: plugins/s3
  settings:
    bucket: lolcator.static.stendahls.se
    access_key: 
      from_secret: AWS_ACCESS_KEY_ID
    secret_key: 
      from_secret: AWS_SECRET_ACCESS_KEY
    region: eu-west-1
    source: build/**/*
    target: /
    strip_prefix: build/
    
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host: https://sonar.stendahls.net
    sonar_token:
      from_secret: SONAR_TOKEN
